### ISSUE TITLE
Flussab-aiger: Wrong writing latches in ASCII mode.

### ISSUE THREAD

**Issue by matszpk** [jix/flussab#3]
In flussab-aiger: Latches has been wrong written in ASCII writer if initialization for latch is None. It that case instead generating:
`10 16 10` it generates `10 1610` - it omit one space. Bug in code:
```
match latch.initialization {
            Some(true) => self.writer.write_all_defer_err(b" 1\n"),
            Some(false) => self.writer.write_all_defer_err(b"\n"),
            None => {
                flussab::write::text::ascii_digits(&mut self.writer, latch.state.code());
                self.writer.write_all_defer_err(b"\n");
            }
        }
```
At None should be written one space.

**Comment by jix** [comment]
Thank you for reporting this!

I merged a fix and did some quick additional testing using the aigfuzz command included with [the aiger tools](https://github.com/arminbiere/aiger), which would also have caught this issue. That didn't find any further issues.

I plan to add included tests with good coverage of all supported features and also finish the documentation for the `flussab-aiger` crate in the next few weeks. At that point I will make a new release on crates.io and will also remove the "preview release" status for `flussab-aiger`.
